### ISSUE TITLE
phpseclib - later versions (>0.3.8)?

### ISSUE THREAD

**Issue by judgej** [thephpleague/flysystem-sftp#12] opened 2015-09-22 17:23 UTC
phpseclib 0.3.8 is a year old now. Versions 1.0.0 and 2.0.0 are now out, and are being used by framewords such as Laravel 5.1. This makes installing flysystem-sftp difficult on modern frameworks.

I don't know what v1 and v2 of phpseclib bring, and whether they would work for flysystem-sftp, but would they be compatible? Could the version requirements be extended?

**Comment by judgej** [comment] 2015-09-22 17:27
Rate of development on phpseclib is pretty crazy. Nice to see, but keeping up is a full time job :-)

**Comment by judgej** [comment] 2015-09-22 17:44
Okay, going crazy - trying to install from a fork with a dependency of phplibsec 2.0 to see if it all works:

``` json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/academe/flysystem-sftp.git"
        }
    ],
    "require": {
        "phpseclib/phpseclib": "^2.0",
        "league/flysystem-sftp": "~1.0"
    }
}
```

Still getting the error:

``` text
  Problem 1
    - league/flysystem-sftp 1.0.6 requires phpseclib/phpseclib ~0.3.8 -> no matching package found.
    - league/flysystem-sftp 1.0.5 requires phpseclib/phpseclib ~0.3.8 -> no matching package found.
    - league/flysystem-sftp 1.0.4 requires phpseclib/phpseclib ~0.3.8 -> no matching package found.
    - league/flysystem-sftp 1.0.3 requires phpseclib/phpseclib ~0.3.8 -> no matching package found.
    - league/flysystem-sftp 1.0.2 requires phpseclib/phpseclib ~0.3.8 -> no matching package found.
    - league/flysystem-sftp 1.0.1 requires phpseclib/phpseclib ~0.3.8 -> no matching package found.
    - league/flysystem-sftp 1.0.0 requires phpseclib/phpseclib ~0.3.7 -> no matching package found.
    - league/flysystem-sftp 1.0.6 requires phpseclib/phpseclib ~0.3.8 -> no matching package found.
    - league/flysystem-sftp 1.0.5 requires phpseclib/phpseclib ~0.3.8 -> no matching package found.
    - league/flysystem-sftp 1.0.4 requires phpseclib/phpseclib ~0.3.8 -> no matching package found.
    - league/flysystem-sftp 1.0.3 requires phpseclib/phpseclib ~0.3.8 -> no matching package found.
    - league/flysystem-sftp 1.0.2 requires phpseclib/phpseclib ~0.3.8 -> no matching package found.
    - league/flysystem-sftp 1.0.1 requires phpseclib/phpseclib ~0.3.8 -> no matching package found.
    - league/flysystem-sftp 1.0.0 requires phpseclib/phpseclib ~0.3.7 -> no matching package found.
    - Installation request for league/flysystem-sftp ~1.0 -> satisfiable by league/flysystem-sftp[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6].
```

It's as though composer is ignoring the repositories section. Why would it do that? Is composer broken - getting its composer.json from packagist even when it's told what repository to in? Ah, no - I need to go to `dev-master`. Dhoh.

Edit: All installed, but must go, will test later.

**Comment by andreybolonin** [comment] 2015-09-22 19:19
https://github.com/thephpleague/flysystem-sftp/pull/11

**Comment by frankdejonge** [comment] 2015-09-22 19:25
@judgej which laravel package uses the phpseclib package? I didn't see anything in the laravel/framework repo.

**Comment by judgej** [comment] 2015-09-22 20:46
Hmm, not sure, maybe it's something else I have installed.

**Comment by judgej** [comment] 2015-09-22 21:01
I can't find anything that uses it, except a direct `require` in my history from a few weeks ago. Maybe I installed it while trying something out and forgot. I've just removed it (2.0.0) and now `league/flysystem-sftp` installs okay by pulling in `phpseclib/phpseclib` (0.3.10).

Right, so what I have now seems to work, and so long as nothing else needs a newer flysytem-sftp then I'm okay. I'll leave it at that for now. Sorry for wasting your time!

It looks like @pilotftzi is on the case with 2.0.0 anyway. Not sure if you want to close this issue, or leave it open as a placeholder for PR #11 ?

**Comment by soee** [comment] 2015-10-09 08:21
If we do not jump to 2.0, flysystem-sftp will fail on PHP7 because of phpseclib. [See this.](https://github.com/thephpleague/flysystem-sftp/issues/14)

**Comment by mediamonks-robert** [comment] 2015-10-22 09:11
I'm having an issue with a sftp server where I can not connect with, it just hangs. This is caused by a bug in phpseclib ~0.3 which was fixed in ~1.0. Please update the dependency :)

**Comment by frankdejonge** [comment] 2015-10-22 09:16
@soee sorry for the wait guys, I'll be tackling this issue tomorrow.

**Comment by frankdejonge** [comment] 2015-10-22 09:17
Sorry for the wait people, been super busy. I'll get this up to date tomorrow, possibly tonight _fingers crossed_.

**Comment by frankdejonge** [comment] 2015-10-25 22:02
It's released as 1.0.7

**Closed as completed by frankdejonge** 2015-10-25 22:02 UTC

**Comment by soee** [comment] 2015-10-25 22:54
@frankdejonge Than you very much! :)

**Comment by mediamonks-robert** [comment] 2015-10-26 16:32
Thanks! :)
