### ISSUE TITLE
SFTP Adapter doesn't support double authentication

### ISSUE THREAD

**Issue by guice** [thephpleague/flysystem-sftp#25] opened 2016-08-25 22:59 UTC
SFTP Fails login when SFTP/SSH server requires double authentication: publickey and password.

Reproduce:
- Validate login works independently with password and ssh key.
- Set `AuthenticationMethods` to `publickey,password` on server.
- Set both `password` and `privatekey` values for SFTP Adapter.

Login fails.

Independently, login works successfully.  It's only when _both_ authentication methods are required does the login fail.

**Comment by guice** [comment] 2016-08-29 18:38
Here's a solution. When `password` && `privateKey` are supplied, use a login method using both:

``` php
class SftpAdapter extends \League\Flysystem\Sftp\SftpAdapter
{
    protected function login()
    {
        if (! $this->connection->login($this->username, $this->getPrivateKey())
            && ! $this->connection->login($this->username, $this->getPassword())) {
            throw new LogicException('Could not login with username: '.$this->username.', host: '.$this->host);
        }
    }
}
```

Obviously update to check for all the other items, like you do. I've removed the Agent check as we're not using Agent forward for our specific use case.

I'll sent a pull request if / when I figure out to do those ... Still new at the whole pull collaboration thing.

**Comment by Stelian** [comment] 2017-02-23 20:38
While this can be implemented, it could cause BC breaks for those who have both keys in the __construct array. @frankdejonge should this be a feature and if yes, how would you implement it?

Thinking of another key to enforce both values being checked to maintain BC compat

**Comment by frankdejonge** [comment] 2017-02-23 21:00
@Stelian I'd consider this a bugfix, as in, it was intended behaviour but it wasn't handled like that. Though it would only need to be done when the password is actually set. In cases where people now have passes a password, which they didn't need because it worked without and would break with it... I imagine that'd be a extremely small group of people.

**Comment by frankdejonge** [comment] 2017-11-21 10:28
Closing this because an connection object can be injected which can have the double authentication.

**Closed as completed by frankdejonge** 2017-11-21 10:28 UTC
Labels: bug
