### ISSUE TITLE
listContents() always return []

### ISSUE THREAD

**Issue by MasterB** [thephpleague/flysystem-sftp#4] opened 2015-02-26 06:40 UTC
If I use "League\Flysystem\Sftp\SftpAdapter" as Adapter then Method listContents() return always a blank array(). Other methods works so far? With "League\Flysystem\Adapter\Ftp" as adapter everything is ok. Any ideas (I use temporary an Snakeoil SSL Zertifikat, I think the phpseclib is the problem)?
Same with v 1.0.0 - 1.0.2

**Comment by frankdejonge** [comment] 2015-03-10 14:37
@MasterB could you get raw result of the rawlist call? That way we might be able to see what's going on.

**Comment by MasterB** [comment] 2015-03-11 06:41
@frankdejonge rawlist call gives me always "false" back. I could follow the error until the phpseclib. I don't now where the problem is at moment. Fileupload works fine with the SftpAdapter.

**Comment by frankdejonge** [comment] 2015-04-16 11:44
@MasterB I'm guessing this is an issue with PHPSeclib, pehaps you can try to recreate the same operation using it directly? This might give you an indication of what's going on internally. Also, maybe you can checkout php's error log, could be that something is ignored. I know phpseclib is php 4-ish so they emit errors on certain stuff.

**Comment by frankdejonge** [comment] 2015-05-26 13:45
@MasterB ping!

**Comment by MasterB** [comment] 2015-05-26 19:35
@frankdejonge yeah, sorry I did not make some further tests. I'm try to live with League\Flysystem\Adapter\Ftp adapter at moment. In near future I'll test the desired SftpAdapter again.

**Comment by frankdejonge** [comment] 2015-05-27 08:13
@MasterB I'll close this issue for now since I can't reproduce this. Feel free to ping to re-open at a later time.

**Closed as completed by frankdejonge** 2015-05-27 08:13 UTC

**Comment by patie** [comment] 2018-09-12 13:47
same problem

**Comment by dorianboulch** [comment] 2021-09-28 12:23
It looks like the Generator doesn't work in SftpAdapter. 
The method `listContents()` isn't called when the yield keyword is present.
I tried by removing it and it works.
By calling the listContents(), the connection to sftp server is not called and the function returns an empty array. 

This doesn't work :
```php
$x = $filesystem->listContents('/');
// $x is an emtpy array
```

But this works :
```php
foreach ($filesystem->listContents('/') as $content){
      var_dump($content); 
}
```

**Comment by frankdejonge** [comment] 2021-09-28 16:06
I've locked this issue, without further information these's not much I can do to help. Please open a new issue in case there is new information.
